# CircleCI 2.0 config for ruby, reference: https://circleci.com/docs/2.0/language-ruby/

version: 2
jobs:

  deploy:
    docker:
      - image: circleci/ruby:2.5.1-node-browse
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
  test:
    docker:
      - image: circleci/ruby:2.5.1-node-browse
    steps:
        - checkout
        - restore_cache:
          keys:
            - bundle-install-{{ checksum "Gemfile.lock"}}
            - bundle-install-
        - run:
          name: install dependencies
          command: bundle install --path vendor/bundle

        - save_cache:
          key: bundle-install-{{ checksum "Gemfile.lock"}}
          paths: vendor/bundle

        - run:
          name: run tests
          command: rspec

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
